//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRate
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private ExchangeRate.FaultMessageList[] FaultMessageListArrayField;
        
        private ExchangeRate.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeRate.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeRate.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private ExchangeRate.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeRate.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private ExchangeRate.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExchangeRate.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ExchangeRate.ExchangeRateForCurrenciesService")]
    public interface ExchangeRateForCurrenciesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExchangeRateForCurrenciesService/getExchangeRateForCurrencies", ReplyAction="http://tempuri.org/ExchangeRateForCurrenciesService/getExchangeRateForCurrenciesR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExchangeRate.AifFault), Action="http://tempuri.org/ExchangeRateForCurrenciesService/getExchangeRateForCurrenciesA" +
            "ifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse> getExchangeRateForCurrenciesAsync(ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExchangeRateForCurrenciesService/getCompanyCurAmount", ReplyAction="http://tempuri.org/ExchangeRateForCurrenciesService/getCompanyCurAmountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExchangeRate.AifFault), Action="http://tempuri.org/ExchangeRateForCurrenciesService/getCompanyCurAmountAifFaultFa" +
            "ult", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse> getCompanyCurAmountAsync(ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ExchangeRate.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _fromCurrency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _toCurrency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime _exchangeDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _cmpId;
        
        public ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest()
        {
        }
        
        public ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest(ExchangeRate.CallContext CallContext, string _fromCurrency, string _toCurrency, System.DateTime _exchangeDate, string _cmpId)
        {
            this.CallContext = CallContext;
            this._fromCurrency = _fromCurrency;
            this._toCurrency = _toCurrency;
            this._exchangeDate = _exchangeDate;
            this._cmpId = _cmpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public decimal response;
        
        public ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse()
        {
        }
        
        public ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse(decimal response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public ExchangeRate.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.DateTime _exchangeDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public decimal _transactionAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _transactionCurrency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _cmpId;
        
        public ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest()
        {
        }
        
        public ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest(ExchangeRate.CallContext CallContext, System.DateTime _exchangeDate, decimal _transactionAmount, string _transactionCurrency, string _cmpId)
        {
            this.CallContext = CallContext;
            this._exchangeDate = _exchangeDate;
            this._transactionAmount = _transactionAmount;
            this._transactionCurrency = _transactionCurrency;
            this._cmpId = _cmpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public decimal response;
        
        public ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse()
        {
        }
        
        public ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse(decimal response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ExchangeRateForCurrenciesServiceChannel : ExchangeRate.ExchangeRateForCurrenciesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ExchangeRateForCurrenciesServiceClient : System.ServiceModel.ClientBase<ExchangeRate.ExchangeRateForCurrenciesService>, ExchangeRate.ExchangeRateForCurrenciesService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExchangeRateForCurrenciesServiceClient() : 
                base(ExchangeRateForCurrenciesServiceClient.GetDefaultBinding(), ExchangeRateForCurrenciesServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_ExchangeRateForCurrenciesService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateForCurrenciesServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ExchangeRateForCurrenciesServiceClient.GetBindingForEndpoint(endpointConfiguration), ExchangeRateForCurrenciesServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateForCurrenciesServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExchangeRateForCurrenciesServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateForCurrenciesServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExchangeRateForCurrenciesServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateForCurrenciesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse> ExchangeRate.ExchangeRateForCurrenciesService.getExchangeRateForCurrenciesAsync(ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest request)
        {
            return base.Channel.getExchangeRateForCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesResponse> getExchangeRateForCurrenciesAsync(ExchangeRate.CallContext CallContext, string _fromCurrency, string _toCurrency, System.DateTime _exchangeDate, string _cmpId)
        {
            ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest inValue = new ExchangeRate.ExchangeRateForCurrenciesServiceGetExchangeRateForCurrenciesRequest();
            inValue.CallContext = CallContext;
            inValue._fromCurrency = _fromCurrency;
            inValue._toCurrency = _toCurrency;
            inValue._exchangeDate = _exchangeDate;
            inValue._cmpId = _cmpId;
            return ((ExchangeRate.ExchangeRateForCurrenciesService)(this)).getExchangeRateForCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse> ExchangeRate.ExchangeRateForCurrenciesService.getCompanyCurAmountAsync(ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest request)
        {
            return base.Channel.getCompanyCurAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountResponse> getCompanyCurAmountAsync(ExchangeRate.CallContext CallContext, System.DateTime _exchangeDate, decimal _transactionAmount, string _transactionCurrency, string _cmpId)
        {
            ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest inValue = new ExchangeRate.ExchangeRateForCurrenciesServiceGetCompanyCurAmountRequest();
            inValue.CallContext = CallContext;
            inValue._exchangeDate = _exchangeDate;
            inValue._transactionAmount = _transactionAmount;
            inValue._transactionCurrency = _transactionCurrency;
            inValue._cmpId = _cmpId;
            return ((ExchangeRate.ExchangeRateForCurrenciesService)(this)).getCompanyCurAmountAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ExchangeRateForCurrenciesService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ExchangeRateForCurrenciesService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://<<yourserver>>:8201/DynamicsAx/Services/ExchangeRateServices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExchangeRateForCurrenciesServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_ExchangeRateForCurrenciesService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExchangeRateForCurrenciesServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_ExchangeRateForCurrenciesService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_ExchangeRateForCurrenciesService,
        }
    }
}
